# Generated by Django 4.1 on 2022-08-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0003_rename_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExcelComp.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='processedfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExcelComp.file'),
        ),
    ]
