# Generated by Django 4.1 on 2022-08-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0005_tag_order_owner_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(to='ExcelComp.tag'),
        ),
    ]
