# Generated by Django 4.1 on 2022-08-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0007_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Feedback',
        ),
    ]
