# Generated by Django 4.1 on 2022-08-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0008_rename_contactus_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedmsg',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='feedname',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
