# Generated by Django 4.1 on 2022-08-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0009_rename_message_feedback_feedmsg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedmail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
