# Generated by Django 4.1 on 2022-08-15 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExcelComp', '0013_remove_file_date_created_remove_file_tags_file_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excfile', models.FileField(null=True, upload_to='ExcelComp/singlefiles')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
