# Generated by Django 4.1 on 2022-08-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0014_excelfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='excfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
