# Generated by Django 4.1 on 2022-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelComp', '0018_remove_processedfiles_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processedfiles',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
