# Generated by Django 4.1 on 2022-08-15 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExcelComp', '0019_alter_excelfiles_owner_alter_processedfiles_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
